const familiares = [
{ 
	id: 0, 
	tags: ["blue"], 
	Nombre: "Basso Caffarini",
	Nacionalidad: "Italiana", 
	Residencia: "",
	img: "./img/Hombre_1.jpg",
	Nacimiento: "./img/Hombre_1.jpg"
},
{ 
	id: 500, 
	pid: 0, 
	tags: ["partner"], 
	Nombre: "Anna Palestini", 
	Nacionalidad: "Italiana",
	img: "./img/Mujer_1.jpg" 
},
{ 
	id: 501, 
	pid: 0,
	ppid: 500,
	tags: ["blue"], 
	Nombre: "Andrea Caffarini",
	Nacionalidad: "Italiana", 
	Residencia: "",
	img: "./img/Hombre_1.jpg",
},
{ 
	id: 550, 
	pid: 501, 
	tags: ["partner"], 
	Nombre: "Rachele De Palma", 
	Nacionalidad: "Italiana",
	img: "./img/Mujer_1.jpg" 
},
{ 
	id: 502, 
	pid: 501,
	ppid: 550,
	tags: ["blue"], 
	Nombre: "Tomasso Caffarini",
	Nacionalidad: "Italiana", 
	Residencia: "",
	img: "./img/Hombre_1.jpg",
},
{ 
	id: 552, 
	pid: 502, 
	tags: ["partner"], 
	Nombre: "María Chiara de Benedectis", 
	Nacionalidad: "Italiana",
	img: "./img/Mujer_1.jpg" 
},
{
	id: 900, 
	pid: 502,
	ppid: 552,
	Nombre: "Nicola Caffarini", 
	img: "./img/Hombre_1.jpg"
},
{
	id: 901, 
	pid: 502,
	ppid: 552,
	Nombre: "Giovanni Caffarini", 
	img: "./img/Hombre_1.jpg"
},
{
	id: 902, 
	pid: 502,
	ppid: 552,
	Nombre: "Titto Caffarini", 
	img: "./img/Hombre_1.jpg"
},
{
	id: 903, 
	pid: 502,
	ppid: 552,
	Nombre: "María Rachele Caffarini", 
	img: "./img/Mujer_1.jpg"
},
{
	id: 904, 
	pid: 502,
	ppid: 552,
	Nombre: "Luis Caffarini", 
	img: "./img/Hombre_1.jpg"
},
{
	id: 905, 
	pid: 502,
	ppid: 552,
	Nombre: "Pedro Caffarini", 
	img: "./img/Hombre_1.jpg"
},
{
	id: 906, 
	pid: 502,
	ppid: 552,
	Nombre: "Ana Caffarini", 
	img: "./img/Mujer_1.jpg"
},
{
	id: 1, 
	pid: 502,
	ppid: 552,
	tags: ["blue"], 
	Nombre: "Domingo Caffarini", 
	Nacionalidad: "Argentina", 
	Residencia: "Hurlingham | Buenos Aires | Argentina", 
	img: "./img/Hombre_1.jpg", 
	Profesión: "Peluquero", 
	Biografía: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
},
{ 
	id: 2, 
	pid: 1, 
	tags: ["partner"], 
	Nombre: "Tita", 
	Nacionalidad: "Argentino", 
	Residencia: "Hurlingham | Buenos Aires | Argentina", 
	Título: "", 
	img: "./img/Mujer_1.jpg" },
{ 
	id: 3, 
	pid:1, 
	ppid: 2, 
	Nombre: "Héctor Caffarini", 
	Nacionalidad: "Argentino",
	Profesión: "Obstetra",
	Residencia: "Mar del Plata | Buenos Aires | Argentina", 
	Título: "", 
	img: "./img/Hombre_1.jpg" },
{ 
	id: 4, 
	pid:1, 
	ppid: 2, 
	Nombre: "Nicolita Caffarini", 
	Título: "", 
	img: "./img/Hombre_1.jpg" },
{ 
	id: 5, 
	pid:1, 
	ppid: 2, 
	Nombre: "Clara Caffarini", 
	Título: "", 
	img: "./img/Mujer_1_inv.jpg" },
{ 
	id: 6, 
	pid:3, 
	tags: ["partner"], 
	Nombre: "Carmen Viloni", 
	Nacionalidad: "Argentina", 
	Residencia: "Mar del Plata | Buenos Aires | Argentina", 
	Título: "", 
	img: "./img/Mujer_1.jpg" },
{ 
	id: 7, 
	pid:3, 
	ppid: 6, 
	Nombre: "Héctor Domingo Caffarini", 
	Nacionalidad: "Argentino",
	Profesión: "Abogado",
	Residencia: "Mar del Plata | Buenos Aires | Argentina", 
	Título: "", 
	img: "./img/Hombre_1.jpg" },
{ 
	id: 8, 
	pid:3, 
	ppid: 6, 
	Nombre: "Beatriz Caffarini", 
	Nacionalidad: "Argentina", 
	Profesión: "Médica",
	Residencia: "Mar del Plata | Buenos Aires | Argentina", 
	Título: "", 
	img: "./img/Mujer_1_inv.jpg" },
{ 
	id: 9, 
	pid:7, 
	tags: ["partner"], 
	Nombre: "Lía Rosa Abeijón", 
	Nacionalidad: "Argentina", 
	Residencia: "Ciudad Autónoma de Buenos Aires | Argentina", 
	Título: "", 
	img: "./img/Mujer_2.jpg" },
{ 
	id: 10,
	pid: 7, 
	ppid: 9, 
	Nombre: "Héctor Nicolás Caffarini", 
	Nacionalidad: "Argentino",
	Profesión: "Programador",
	Residencia: "Ciudad Autónoma de Buenos Aires | Argentina", 
	Título: "", 
	img: "./img/hectornicolascaffarini.jpg", 
	Contacto: "hncaffarini@gmail.com" },
{ 
	id: 11,
	pid:8, 
	tags: ["partner"], 
	Nombre: "Darío Chierichetti", 
	Nacionalidad: "Argentino",
	Residencia: "Mar del Plata | Buenos Aires | Argentina", 
	Título: "",
	Profesión: "Cirujano",
	img: "./img/Hombre_1_inv.jpg" },
{ 
	id: 12,
	pid: 4, 
	Nombre: "Patricia Caffarini",
	img: "./img/Mujer_1.jpg" },
{ 
	id: 13,
	pid: 5, 
	tags: ["partner"],
	Nombre: "Enrique Di Leone",
	img: "./img/Hombre_1_inv.jpg" }
]