const familiares = [
{ 
	id: 0, 
	tags: ["blue"], 
	Nombre: "Basso Caffarini",
	Nacionalidad: "Italiana",
	Profesión: "Marinero",
	LugarNacimiento: "San Benedetto del Tronto",
	LinkNacimiento: "https://es.wikipedia.org/wiki/San_Benedetto_del_Tronto",
	img: "./img/Hombre_1.jpg",
	Nacimiento: "./img/Hombre_1.jpg"
},
{ 
	id: 500, 
	pid: 0, 
	tags: ["partner"], 
	Nombre: "Anna Palestini", 
	Nacionalidad: "Italiana",
	Profesión: "Hilandera",
	img: "./img/Mujer_1.jpg" 
},
{ 
	id: 501, 
	pid: 0,
	ppid: 500,
	tags: ["blue"], 
	Nombre: "Andrea Caffarini",
	Nacionalidad: "Italiana", 
	LugarNacimiento: "San Benedetto del Tronto",
	LinkNacimiento: "https://es.wikipedia.org/wiki/San_Benedetto_del_Tronto",
	Profesión: "Marinero",
	img: "./img/Hombre_1.jpg",
},
{ 
	id: 550, 
	pid: 501, 
	tags: ["partner"], 
	Nombre: "Rachele De Palma",
	Nacionalidad: "Italiana",
	Profesión: "Hilandera",
	img: "./img/Mujer_1.jpg" 
},
{ 
	id: 502, 
	pid: 501,
	ppid: 550,
	tags: ["blue"], 
	Nombre: "Tomasso Caffarini",
	Profesión: "Zapatero",
	Nacionalidad: "Italiana",
	LugarNacimiento: "Ortona",
	LinkNacimiento: "https://es.wikipedia.org/wiki/Ortona",
	Residencia: "",
	img: "./img/tomasso_1.jpg",
},
{ 
	id: 552, 
	pid: 502, 
	tags: ["partner"], 
	Nombre: "María Chiara de Benedectis", 
	Nacionalidad: "Italiana",
	Profesión: "Hilandera",
	img: "./img/maria_chiara_1.jpg" 
},
{ 
	id: 530,
	pid: 501,
	ppid: 550,
	Nombre: "Teresa Caffarini",
	Nacionalidad: "Italiana",
	LugarNacimiento: "Ortona",
	LinkNacimiento: "https://es.wikipedia.org/wiki/Ortona",
	img: "./img/Mujer_1.jpg",
},
{ 
	id: 512,
	pid: 501,
	ppid: 550,
	Nombre: "Rocco Caffarini",
	Profesión: "Marinero",
	Nacionalidad: "Italiana",
	LugarNacimiento: "Ortona",
	LinkNacimiento: "https://es.wikipedia.org/wiki/Ortona",
	img: "./img/Hombre_1.jpg",
},
{ 
	id: 522,
	pid: 512,
	tags: ["partner"], 
	Nombre: "Filomena Primavera", 
	Nacionalidad: "Italiana",
	img: "./img/Mujer_1.jpg"
},
{ 
	id: 513,
	pid: 512,
	ppid: 522,
	Nombre: "Agostino Caffarini",
	FechaNacimiento: "1878",
	FechaDefuncion: "1882",
	img: "./img/Hombre_1.jpg",
},
{ 
	id: 514,
	pid: 512,
	ppid: 522,
	Nombre: "Alfredo Caffarini",
	FechaNacimiento: "1883",
	img: "./img/Hombre_1.jpg",
},
{ 
	id: 515,
	pid: 512,
	ppid: 522,
	Nombre: "Ernesto Caffarini",
	FechaNacimiento: "1886",
	img: "./img/Hombre_1.jpg",
},
{
	id: 900, 
	pid: 502,
	ppid: 552,
	Nombre: "Nicola Caffarini",
	Nacimiento: "09/12/1876",
	FechaCasamiento: "1904",
	Profesión: "Telegrafista",
	FechaDefuncion: "06/01/1968",
	img: "./img/Hombre_1.jpg"
},
{ 
	id: 920, 
	pid: 900, 
	tags: ["partner"], 
	Nombre: "Celedonia García", 
	Nacionalidad: "Italiana",
	FechaCasamiento: "1904",
	img: "./img/Mujer_1.jpg"
},
{
	id: 901, 
	pid: 502,
	ppid: 552,
	Nombre: "Giovanni Caffarini",
	FechaNacimiento: "1878",
	img: "./img/Hombre_1.jpg"
},
{
	id: 902, 
	pid: 502,
	ppid: 552,
	Nombre: "Titto Caffarini",
	FechaNacimiento: "1881",
	img: "./img/Hombre_1.jpg"
},
{
	id: 903, 
	pid: 502,
	ppid: 552,
	Nombre: "María Rachele Caffarini", 
	FechaNacimiento: "31/01/1883",
	img: "./img/marietta_1.jpg"
},
{
	id: 850,
	pid: 903,
	tags: ["partner"], 
	Nombre: "Martín Christin",
	img: "./img/Hombre_1.jpg"
},
{
	id: 851, 
	pid: 903,
	ppid: 850,
	Nombre: "Horacio Pedro Christin", 
	img: "./img/Hombre_1.jpg"
},
{
	id: 852, 
	pid: 903,
	ppid: 850,
	Nombre: "Elvira Christin", 
	img: "./img/Mujer_1.jpg"
},
{
	id: 853, 
	pid: 903,
	ppid: 850,
	Nombre: "Héctor Sixto Christin", 
	img: "./img/Hombre_1.jpg"
},
{
	id: 904, 
	pid: 502,
	ppid: 552,
	Nombre: "Luis Tito Caffarini",
	Profesión: "Ingeniero Civil",
	FechaNacimiento: "1894",
	FechaDefuncion: "1980",
	Nacionalidad: "Argentina",
	LugarNacimiento: "San Isidro",
	LinkNacimiento: "https://es.wikipedia.org/wiki/San_Isidro_(Buenos_Aires)",
	img: "./img/luis_tito_padre_1.jpg"
},
{
	id: 905, 
	pid: 502,
	ppid: 552,
	Nombre: "Pedro Caffarini",
	FechaDefuncion: "08/09/1982",
	img: "./img/pedro_1.jpg"
},
{
	id: 915,
	pid: 905,
	tags: ["partner"], 
	Nombre: "Elba Lidia",
	img: "./img/Mujer_1.jpg"
},
{
	id: 906, 
	pid: 502,
	ppid: 552,
	Nombre: "Ana Caffarini", 
	img: "./img/ana_1.jpg"
},
{
	id: 1, 
	pid: 502,
	ppid: 552,
	tags: ["blue"], 
	Nombre: "Domingo Caffarini", 
	Nacionalidad: "Argentina", 
	Residencia: "Hurlingham | Buenos Aires | Argentina", 
	img: "./img/domingo_1.jpg", 
	Profesión: "Peluquero",
	FechaDefuncion: "27/08/1936",
	CausaDefuncion: "Operación de apéndice",
	Biografía: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
},
{ 
	id: 2, 
	pid: 1, 
	tags: ["partner"], 
	Nombre: "Tita", 
	Nacionalidad: "Argentino", 
	Residencia: "Hurlingham | Buenos Aires | Argentina", 
	Título: "", 
	img: "./img/Mujer_1.jpg" },
{ 
	id: 3, 
	pid:1, 
	ppid: 2, 
	Nombre: "Héctor Caffarini", 
	Nacionalidad: "Argentino",
	Profesión: "Obstetra",
	Residencia: "Mar del Plata | Buenos Aires | Argentina", 
	FechaNacimiento: "11/07/1897",
	img: "./img/Hombre_1.jpg" },
{ 
	id: 4, 
	pid:1, 
	ppid: 2, 
	Nombre: "Nicolita Caffarini", 
	FechaDefuncion: "1958-1960",
	img: "./img/Hombre_1.jpg" },
{ 
	id: 5, 
	pid:1, 
	ppid: 2, 
	Nombre: "Clara Caffarini", 
	Título: "", 
	img: "./img/Mujer_1_inv.jpg" },
{ 
	id: 6, 
	pid:3, 
	tags: ["partner"], 
	Nombre: "Carmen Viloni", 
	Nacionalidad: "Argentina", 
	Residencia: "Mar del Plata | Buenos Aires | Argentina", 
	Título: "", 
	img: "./img/Mujer_1.jpg" },
{ 
	id: 7, 
	pid:3, 
	ppid: 6, 
	Nombre: "Héctor Domingo Caffarini", 
	Nacionalidad: "Argentino",
	Profesión: "Abogado",
	Residencia: "Mar del Plata | Buenos Aires | Argentina", 
	Título: "", 
	img: "./img/Hombre_1.jpg" },
{ 
	id: 8, 
	pid:3, 
	ppid: 6, 
	Nombre: "Beatriz Caffarini", 
	Nacionalidad: "Argentina", 
	Profesión: "Médica",
	Residencia: "Mar del Plata | Buenos Aires | Argentina", 
	Título: "",
	img: "./img/Mujer_1_inv.jpg" },
{ 
	id: 9, 
	pid:7, 
	tags: ["partner"], 
	Nombre: "Lía Rosa Abeijón", 
	Nacionalidad: "Argentina", 
	Residencia: "Ciudad Autónoma de Buenos Aires | Argentina", 
	Título: "", 
	img: "./img/Mujer_2.jpg" },
{ 
	id: 10,
	pid: 7, 
	ppid: 9, 
	Nombre: "Héctor Nicolás Caffarini", 
	Nacionalidad: "Argentina",
	Profesión: "Programador",
	Residencia: "Ciudad Autónoma de Buenos Aires | Argentina",
	LugarNacimiento: "Mar del Plata",
	LinkNacimiento: "https://es.wikipedia.org/wiki/Mar_del_Plata",
	Título: "", 
	img: "./img/hectornicolascaffarini.jpg", 
	Contacto: "hncaffarini@gmail.com" },
{ 
	id: 11,
	pid:8, 
	tags: ["partner"], 
	Nombre: "Darío Chierichetti", 
	Nacionalidad: "Argentino",
	Residencia: "Mar del Plata | Buenos Aires | Argentina", 
	Título: "",
	Profesión: "Cirujano",
	img: "./img/Hombre_1_inv.jpg" },
{ 
	id: 12,
	pid: 4, 
	Nombre: "Patricia Caffarini",
	img: "./img/Mujer_1.jpg" },
{ 
	id: 13,
	pid: 5, 
	tags: ["partner"],
	Nombre: "Enrique Di Leone",
	img: "./img/Hombre_1_inv.jpg" },
{
	id: 907, 
	pid: 904,
	Nombre: "Luis Tito Caffarini",
	Profesión: "Arquitecto",
	FechaNacimiento: "1931",
	FechaDefuncion: "2003",
	Nacionalidad: "Argentina",
	img: "./img/luis_tito_hijo_1.jpg" },
{
	id: 908, 
	pid: 907,
	Nombre: "Luis Alejandro Caffarini",
	Profesión: "Intérprete",
	FechaNacimiento: "1964",
	LugarNacimiento: "Ciudad Autónoma de Buenos Aires",
	LinkNacimiento: "https://es.wikipedia.org/wiki/Buenos_Aires",
	Nacionalidad: "Argentina",
	img: "./img/Hombre_1.jpg" }
]